<?php

/**
 * PluginskFormTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginskFormTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginskFormTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginskForm');
    }

    public function getMember($id)
    {
        $q = $this->getTable()
            ->createQuery()
            ->select('b.*')
            ->from('skFormMember b')
            ->where('b.sk_form_id = ?', array($this->id))
            ->andWhere('b.id = ?', array($id))
            ;

        return $q->fetchOne();
    }

    /**
     * @return Doctrine_Collection
     */
    public static function getAllExcept($obj = null)
    {
        $q = Doctrine_Query::create()
            ->select('b.*')
            ->from('skForm b');

        if ( !is_null($obj) )
            $q->where('b.id != ?', array($obj->id));

        return $q->execute();
    }

    /**
     * @return Doctrine_Collection
     */
    public static function getAllForms()
    {
        return self::getAllExcept();
    }

}