<?php

/**
 * PluginskFormMemberTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginskFormMemberTable extends Doctrine_Table
{
  /**
   * The choices for the type field
   *
   */
  protected static $type_choices = array(
                 //'title'       => 'Title',
                 'text'        => 'Textbox',   // max_char, class, required
                 'email'       => 'Email',     // max_char, class, required
                 'url'         => 'URL',       // max_char, class, required
                 'textarea'    => 'Textarea',  // max_char, class, required, html, html_options
                 'tarih'       => 'Date-Time', // date, time, date_format, time_format, range, required, max, min, max_error, min_error
                 'numeric'     => 'Number',    // allow_float, min, max, min_error, max_error,
                 'combo'       => 'Combo',     // items, item_values, include_empty, required,
                 'checkbox'    => 'Checkbox',  // selected_value,
                 'radio'       => 'Radio',     // items, item_values, required
  				);

  /**
   * Returns the choices for the type field
   *
   * @return array
   */
  static function getTypeChoices($empty = false)
  {
    return $empty ? array_merge(array(0 => 'Choose'), self::$type_choices) : self::$type_choices;
  }

  public static function getMemberType($type)
  {
      return array_key_exists($type, self::$type_choices) ? self::$type_choices[$type] : '';
  }

    /**
     * Returns an instance of this class.
     *
     * @return object PluginskFormMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginskFormMember');
    }
}