<?php

/**
 * PluginskFormDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginskFormDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginskFormDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginskFormData');
    }
}