<?php

/**
 * PluginskForm
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginskForm extends BaseskForm
{
    public function getFormMembersOrdered()
    {
        $q = $this->getTable()
  			  ->createQuery()
  			  ->select('b.*')
  			  ->from('skFormMember b')
  			  ->where('b.sk_form_id = ?', array($this->id))
  			  ->orderBy('b.position')
  			  ;

  	    return $q->execute();
    }

    /**
     *
     * @return multitype:mixed
     */
    public function parseEmails()
    {
        $return = array();
        $array = explode("\n", $this->emails);
        if ( count($array) == 1 ) {
            $array = explode("\r", $this->emails);
        }
        foreach($array as $item)
        {
            $return[] = str_replace('%domain%', sfContext::getInstance()->getUser()->getDomain(), str_replace("\r", "", str_replace("\n", "", $item)));
        }

        return $return;
    }

    /**
     *
     * @throws sfException
     * @return sfForm
     */
    public function initializeForm() {
        $class = sfConfig::get('app_sk_custom_forms_plugin_form_renderer_class', 'skCustomFormsMemberRenderer');

        if ( !class_exists($class) )
        {
            throw new sfException(sprintf('Class %s does not exist.', $class));
        }

        $form = new $class(null, array('members' => $this->getFormMembersOrdered(), 'form_object' => $this));

        if ( !is_subclass_of($form, 'skCustomFormsMemberBaseRenderer') )
        {
            throw new sfException(sprintf('Class %s should be extended from skCustomFormsMemberBaseRenderer.', $class));
        }

        return $form;
    }

}