<?php

/**
 * PluginskFormMember
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginskFormMember extends BaseskFormMember
{
    /**
     *
     * @param integer $id
     * @return void
     */
    public function copyToForm($id)
    {
        $newMember = $this->copy(false);
        $newMember->sk_form_id = $id;
        $newMember->save();

        $user = sfContext::getInstance()->getUser();
        $eski_culture = $user->getCulture();

        foreach ( sfConfig::get('app_cultures_enabled') as $culture => $title )
        {
            $user->setCulture($culture);
            $newMember->label = $this->label;
            $newMember->description = $this->description;
            $newMember->save();
        }

        $user->setCulture( $eski_culture );
    }

    /**
     * @return void
     */
    public function doDefaults()
    {
        foreach ($this->getDefaultValues() as $fieldName => $value)
        {
            $orig_value = $this->get($fieldName);
            if ( '' === $orig_value || 0 === $orig_value || null === $orig_value )
            {
                $this->set($fieldName, $value);
            }
        }
    }

    /**
     * @return array
     */
    private function getDefaultValues()
    {
        $now = new DateTime();
        $now->modify('-1 month');
        $a = $now->format('Y/m/d');
        $now->modify('+2 month');
        $b = $now->format('Y/m/d');

        return array(
                'tip' => 'text',
                'max' => '0',
                'is_date' => '1',
                'is_time' => '0',
                'date_format' => '%month%/%day%/%year%',
                'time_format' => '%hour%:%minute%',
                'max_date' => $b,
                'min_date' => $a,
                'min' => '0',
                'allow_float' => '1',
                'include_empty' => '1',
                );
    }


}
