<?php

/**
 * PluginskFormMemberDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginskFormMemberDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginskFormMemberDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginskFormMemberData');
    }
}